### ISSUE TITLE
您好，请教下数据采集机制

### ISSUE THREAD

**Issue by beclass** [niugengyun/easytbk#14]
请教下采集机制怎么实现呢？ 比如过期数据自动清空，淘宝那边数据有修改要覆盖本地的。

**Comment by flutterbest** [comment]
我这边用py写的 每两分钟爬取一次

**Comment by beclass** [comment]
新的直接覆盖旧的吗？有对比机制么

**Comment by flutterbest** [comment]
有的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Moonlit <notifications@github.com&gt;
发送时间: 2019年11月13日 18:53
收件人: niugengyun/easytbk <easytbk@noreply.github.com&gt;
抄送: Debug <515343908@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[niugengyun/easytbk] 您好，请教下数据采集机制 (#14)




新的直接覆盖旧的吗？有对比机制么

**Comment by flutterbest** [comment]
我这边的只会爬取新增的优惠券，两分钟更新一次
