### ISSUE TITLE
stream_socket_client() has been disabled for security reasons

### ISSUE THREAD

**Issue by hqin2013** [niugengyun/easytbk#22]
你好：

唯品会接口使用的stream_socket_client()函数，被阿里云禁用了，有无其他办法？

代码在：/vendor/niugengyun/easytbk/src/vip/Osp/Http/HttpClient.php 104行

谢谢

**Comment by flutterbest** [comment]
唯品会自身的SDK写的就很乱 里面有很多函数都是老的

你这边需改php.ini  把禁用的这个函数关了应该就行了

**Comment by hqin2013** [comment]
正式环境是阿里云虚拟主机，跟他们提了ticket，但是回复不允许，说是要我改用curl。。。脑阔疼
