### ISSUE TITLE
您好,可以全局使用https或者配置项有个地方可以配置https地址吗

### ISSUE THREAD

**Issue by liucong2013** [niugengyun/easytbk#45]
因为淘宝客有些地方必须要https访问
虽然可以用execute的第三个参数修改为https地址,但是用起来还是有点别扭
{#1388 ▼
  +"code": 22
  +"msg": "Invalid method:taobao.top.auth.token.create 仅支持https调用"
  +"request_id": "14i728dkubl69"
}

**Comment by flutterbest** [comment]
done

**Comment by liucong2013** [comment]
thanks
