### ISSUE TITLE
vip  composer error  UnionPidService.php does not comply with psr-4 autoloading standard. Skipping.

### ISSUE THREAD

**Issue by killjin** [niugengyun/easytbk#46]
Class NiuGengYun\EasyTBK\vip\request\UnionPidService_queryPid_result located in ./vendor/niugengyun/easytbk/src/vip/request/UnionPidService.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by flutterbest** [comment]
这个没影响，唯品会官方提供的sdk太烂了，一个php文件里面包含了多个class

https://exerror.com/basecontroller-php-does-not-comply-with-psr-4-autoloading-standard-skipping/
